name: Daily DESCO Balance Check

on:
  schedule:
    - cron: "5 2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: desco  # Add this line
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python check_balance.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ACCOUNT_NO: ${{ secrets.ACCOUNT_NO }}
